[[plugins]]
package = "@netlify/plugin-gatsby"

[context.production.environment]
GATSBY_PRISMIC_ACCESS_TOKEN = "MC5ZVC10VWhJQUFDc0FQSTE3.VO-_vQEt77-9F--_ve-_vTQY77-977-9fCl977-9Dgdt77-977-9Ye-_vSPvv71UAe-_ve-_vRke77-9"
GATSBY_PRISMIC_REPOSITORY_NAME = "honolulu-pride"
GOOGLE_MEASUREMENT_ID = "G-G4K6Y1QGWY"
AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"
TYPEKIT_PROJECT_ID = "bry3kbj"
CLIENT_DOCS_URL = "https://honolulupride-docs.netlify.app"

[[redirects]]
from = "https://www.honolulupride.com/*"
to = "https://hawaiilgbtlegacyfoundation.com/"
status = 302
force = true

[[redirects]]
from = "https://honolulupride.com/*"
to = "https://hawaiilgbtlegacyfoundation.com/"
status = 302
force = true

